# Generated by Django 3.2.18 on 2023-07-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_agerecommend_assetrecommend_salaryrecommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agerecommend',
        ),
        migrations.DeleteModel(
            name='AssetRecommend',
        ),
        migrations.DeleteModel(
            name='SalaryRecommend',
        ),
    ]
